# -*- coding: utf-8 -*-
"""dsa2.cpp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rHswBFGjvWqe1vSY0MbWRh6XWAKyrn4
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dsa2.cpp
# #include <iostream>
# #include <unordered_set>
# using namespace std;
# 
# int main() {
#     int nums[] = {1,2,3,1};
#     unordered_set<int> s;
#     bool flag = false;
# 
#     for(int i=0;i<4;i++) {
#         if(s.count(nums[i])>0) {
#             flag = true;
#             break;
#         }
#         s.insert(nums[i]);
#     }
# 
#     if(flag) cout<<"true";
#     else cout<<"false";
# }
#

!g++ dsa2.cpp -o output
!./output

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dsa.cpp
# #include <iostream>
# #include <unordered_set>
# using namespace std;
# 
# int main() {
#     int A[4] = {1,2,3,4};
#     int B[4] = {3,4,5,6};
#     unordered_set<int> s;
# 
#     for(int i=0;i<4;i++) s.insert(A[i]);
# 
#     for(int i=0;i<4;i++)
#         if(s.count(B[i])>0) cout<<B[i]<<" ";
# }
# 
#

!g++ dsa.cpp -o output
!./output

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dsa.cpp
# #include <iostream>
# #include <unordered_map>
# using namespace std;
# 
# int main() {
#     int nums[6] = {2,3,2,4,3,2};
#     unordered_map<int,int> mp;
# 
#     for(int i=0;i<6;i++)
#         mp[nums[i]]++;
# 
#     for(auto x: mp)
#         cout<<x.first<<" -> "<<x.second<<" times"<<endl;
# }
#

!g++ dsa.cpp -o output
!./output

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dsa.cpp
# #include <iostream>
# #include <unordered_map>
# using namespace std;
# 
# int main() {
#     int arr[6] = {4,5,1,2,0,4};
#     unordered_map<int,int> mp;
# 
#     for(int i=0;i<6;i++)
#         mp[arr[i]]++;
# 
#     for(int i=0;i<6;i++)
#         if(mp[arr[i]]==1) {
#             cout<<arr[i];
#             break;
#         }
# }
#

!g++ dsa.cpp -o output
!./output

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dsa.cpp
# #include <iostream>
# #include <unordered_set>
# using namespace std;
# 
# struct Node {
#     int data;
#     Node* next;
# };
# 
# int main() {
#     Node *a = new Node{1,NULL};
#     Node *b = new Node{2,NULL};
#     Node *c = new Node{3,NULL};
#     Node *d = new Node{4,NULL};
# 
#     a->next = b;
#     b->next = c;
#     c->next = d;
#     d->next = b;
# 
#     unordered_set<Node*> st;
#     Node* temp = a;
#     bool loop = false;
# 
#     while(temp != NULL) {
#         if(st.count(temp)>0) {
#             loop = true;
#             break;
#         }
#         st.insert(temp);
#         temp = temp->next;
#     }
# 
#     if(loop) cout<<"true";
#     else cout<<"false";
# }
#

!g++ dsa.cpp -o output
!./output

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dsa.cpp
# #include <iostream>
# #include <unordered_set>
# using namespace std;
# 
# struct Node {
#     int data;
#     Node *left, *right;
# };
# 
# bool check(Node* root, unordered_set<int> &s) {
#     if(root == NULL) return false;
#     if(s.count(root->data)>0) return true;
#     s.insert(root->data);
#     return check(root->left,s) || check(root->right,s);
# }
# 
# int main() {
#     Node *root = new Node{5,NULL,NULL};
#     root->left = new Node{3,NULL,NULL};
#     root->right = new Node{7,NULL,NULL};
#     root->left->left = new Node{3,NULL,NULL};
# 
#     unordered_set<int> s;
# 
#     if(check(root,s)) cout<<"Duplicates Found";
#     else cout<<"No Duplicates";
# }
#

!g++ dsa.cpp -o output
!./output